// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pokedle.Api.Infrastructure;

#nullable disable

namespace Pokedle.Api.Migrations
{
    [DbContext(typeof(PokedleContext))]
    [Migration("20260326163731_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pokedle.Api.Domain.ElementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_element_types");

                    b.ToTable("element_types", (string)null);
                });

            modelBuilder.Entity("Pokedle.Api.Domain.Habitat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_habitats");

                    b.ToTable("habitats", (string)null);
                });

            modelBuilder.Entity("Pokedle.Api.Domain.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("integer")
                        .HasColumnName("color_id");

                    b.Property<int>("EvolutionStage")
                        .HasColumnType("integer")
                        .HasColumnName("evolution_stage");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<int>("HabitatId")
                        .HasColumnType("integer")
                        .HasColumnName("habitat_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_pokemons");

                    b.HasIndex("ColorId")
                        .HasDatabaseName("ix_pokemons_color_id");

                    b.HasIndex("HabitatId")
                        .HasDatabaseName("ix_pokemons_habitat_id");

                    b.ToTable("pokemons", (string)null);
                });

            modelBuilder.Entity("Pokedle.Api.Domain.PokemonColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_colors");

                    b.ToTable("colors", (string)null);
                });

            modelBuilder.Entity("Pokedle.Api.Domain.PokemonElementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ElementTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("element_type_id");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer")
                        .HasColumnName("pokemon_id");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.HasKey("Id")
                        .HasName("pk_pokemon_element_types");

                    b.HasIndex("ElementTypeId")
                        .HasDatabaseName("ix_pokemon_element_types_element_type_id");

                    b.HasIndex("PokemonId", "Slot")
                        .IsUnique()
                        .HasDatabaseName("ix_pokemon_element_types_pokemon_id_slot");

                    b.ToTable("pokemon_element_types", (string)null);
                });

            modelBuilder.Entity("Pokedle.Api.Domain.Pokemon", b =>
                {
                    b.HasOne("Pokedle.Api.Domain.PokemonColor", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pokemons_colors_color_id");

                    b.HasOne("Pokedle.Api.Domain.Habitat", "Habitat")
                        .WithMany()
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pokemons_habitats_habitat_id");

                    b.Navigation("Color");

                    b.Navigation("Habitat");
                });

            modelBuilder.Entity("Pokedle.Api.Domain.PokemonElementType", b =>
                {
                    b.HasOne("Pokedle.Api.Domain.ElementType", "ElementType")
                        .WithMany()
                        .HasForeignKey("ElementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pokemon_element_types_element_types_element_type_id");

                    b.HasOne("Pokedle.Api.Domain.Pokemon", "Pokemon")
                        .WithMany("PokemonElementTypes")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pokemon_element_types_pokemons_pokemon_id");

                    b.Navigation("ElementType");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("Pokedle.Api.Domain.Pokemon", b =>
                {
                    b.Navigation("PokemonElementTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
